FROM nginx
WORKDIR /apps
RUN echo "<h1>This is My First DockerImage build by Dockerfile</h1>" > /usr/share/nginx/html/index.html
RUN mkdir /docs
RUN apt-get update
RUN apt-get install tree











